name: Load secrets from ZV
description: Make secrets from ZV Connect available as environment variables in the next steps.
author: ZV
branding:
  icon: lock
  color: blue
inputs:
  master-password:
    description: master password for zv
  unset-previous:
    description: Whether to unset environment variables populated by ZV in earlier job steps
    default: "false"
  export-env:
    description: Export the secrets as environment variables
    default: "true"
runs:
  using: composite
  steps:
    - shell: bash
      env:
        MASTERPASS: ${inputs.master-password}
      run: |
          unzip ./zv_cli.zip
          ls -a
  
