name: Load secrets from ZV
description: Make secrets from ZV Connect available as environment variables in the next steps.
author: ZV
branding:
  icon: lock
  color: blue
inputs:
  unset-previous:
    description: Whether to unset environment variables populated by ZV in earlier job steps
    default: "false"
  export-env:
    description: Export the secrets as environment variables
    default: "true"
    
jobs:
  example_job:
 
    runs-on: ubuntu-latest
    outputs:
     username: ${{steps.export.outputs.username}}
     password: ${{steps.export.outputs.password}}
    steps:
      - name: actions checkout
        uses: actions/checkout@v4.1.5
        with:
          repository: naveennv2k/ZVSecretsLoading   # Replace with the owner and repository name
          ref: main 
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'    
      - name: unzip cli
        run : unzip ./zv_cli.zip
      - name: login to  zv 
        run: |
              ./zv login
      - name: unlock zv      
        run: printf ${{ secrets.master_password }} | ./zv unlock
      - name: load secrets from zv
        
        run: |
              ls -a $GITHUB_WORKSPACE
              npm install @actions/core
              node ./LoadSecrets.js ${{ inputs.secretName }}
            
      - name: export Secrets
        id: export
        run: |
         echo "username=$secretUsername" >> $GITHUB_OUTPUT
          echo password=$(gpg --symmetric --batch --passphrase "SECRET" --output - <(echo $secretPassword) | base64 -w0) >> $GITHUB_OUTPUT 
      
  
