name: Example Workflow
on: 
  workflow_call:
    inputs:
      secretName:
        required: true
        type: string
   

    

jobs:
  example_job:
    environment: Test
    runs-on: ubuntu-latest
   
    steps:
      - name: actions checkout
        uses: actions/checkout@v4.1.5
      - name: view mass var
        run: echo "secret is ${{ vars.MASTER_PASSWORD }}" 
      - name: view mass secret
        run: echo "secret is ${{ vars.MASTER_PASSWORD }}"
      - name: unzip cli
        run : unzip ./zv_cli.zip
      - name: login to  zv 
        run: |
              ./zv login
      - name: unlock zv      
        run: printf ${{ vars.MASTERPASS }} | ./zv unlock
      - name: load secrets from zv
        run: node loadSecrets.js myPassword
      - name:  printing secrets
        run: echo  $secretUsername
            
      
        
