name: Example Workflow
on: 
  workflow_call:
     inputs:
      secretName:
        required: true
        type: string
     secrets:
       master_password:
        required: true
   

    

jobs:
  example_job:
 
    runs-on: ubuntu-latest
   
    steps:
      - name: actions checkout
        uses: actions/checkout@v4.1.5
        with:
          repository: naveennv2k/ZVSecretsLoading   # Replace with the owner and repository name
          ref: main 
      - name: view mass var
        run: echo "secret is ${{ inputs.secretName }}" 
      - name: view mass secret
        run: echo "secret is ${{ secrets.master_password }}"
      - name: List Workspace Contents
        run: ls -a $GITHUB_WORKSPACE
 
      - name: ls
        run: 
              ls -a
      - name: unzip cli
        run : unzip ./zv_cli.zip
      - name: login to  zv 
        run: |
              ./zv login
      - name: unlock zv      
        run: printf ${{ secrets.master_password }} | ./zv unlock
      - name: load secrets from zv
        run: node ./src/loadSecrets.js ${{ inputs.secretName }}
      - name:  printing secrets
        run: echo  $secretUsername
            
      
        
