name: Example Workflow
on: [workflow_call]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: actions checkout
        uses: actions/checkout@v4.1.5
      - name: sample Test
        run: echo "its calling"
