name: Example Workflow
on: 
  workflow_call:
    outputs: 
      var1:
        description: var1
        value: ${{jobs.example_job.outputs.var1}}

    

jobs:
  example_job:
    runs-on: ubuntu-latest
    outputs:
      var1: $build
    steps:
      - name: actions checkout
        uses: actions/checkout@v4.1.5
      - name: sample Test
        run: echo "its calling"
