
name: main yaml

on: 
  workflow_call:
    inputs:
      secretName:
        required: true
        type: string
   

    

jobs:
  example_job:
 
    runs-on: ubuntu-latest
   
    steps:
      - name: actions checkout
        uses: actions/checkout@v4.1.5
      - name: view mass var
        run: echo "secret is ${{ github.event.inputs.secretName }}" 
      
      
            
